### PR TITLE
Cleanup Interaction > Animation

### LINKED ISSUE #290: Cleanup Interaction > Animation
Proofread and check links

### PR DESCRIPTION
**Pull request by bobbinrobyn**
Resolves #290 

CHANGELOG
:art: Cleanup typos and add URLs for links

### CODE REVIEW

**Comment by ryanbrownhill** [comment]
:+1: look good to me and :boy: says it good to go

**Comment by bobbinrobyn** [comment]
Yep @Snugug. That's better.

**Comment by bobbinrobyn** [comment]
Is there something I need to do to help this build? :expressionless:

**Comment by Snugug** [comment]
Screw you, Travis.

**Pull request merged**
