### PR TITLE
Feature/visual accessibility guidelines

### PR DESCRIPTION
**Pull request by britanyponvelle**
Guidelines for determining accessible colors, ratios, and meeting requirements.

### CODE REVIEW

**Comment by Snugug** [comment]
* All images should be uploaded and included in a `language/images/visual` folder (or something similar).
* Assets (like the `.ase` files) should be uploaded to `language/assets/visual` folder (or something similar).
* My comments on [monospace fonts and font combinations](https://github.com/IBM-Watson/design-library/issues/120#issuecomment-85724015) was not addressed
* There appears to be significant overlap between this, #132, and #131. To the point that the other two are more or less entirely covered by this PR. Is that correct?

**Comment by britanyponvelle** [comment]
I added an images and assets folder, but I'm not sure the best way to push those. Do I make additional branches for each of those?

Agreed there is a lot of overlap for accessibility. I broke it up into it's own section because we are referencing both color and typography. The thought was that it could be easier to find the tools if it was in it's own section.

**Comment by Snugug** [comment]
Add them into this branch, commit, and push. They'll show up here.

What I mean by overlap its like I literally think the same files are in both

**Comment by britanyponvelle** [comment]
@Snugug ahh I see.  In the accessibility section, I meant to replace the IBM Design color page with this: http://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html

That is the resource IBM lists in the Design Language. I can switch them out today

**Comment by Snugug** [comment]
Is that resource available outside of the IBM firewall?

**Comment by Snugug** [comment]
Everything looks good!

**Pull request merged**
