### PR TITLE
Feature/animation library

### PR DESCRIPTION
**Pull request by ryanbrownhill**
PR for the animation variables and documentation for the animation mixin

### CODE REVIEW

**Comment by ryanbrownhill** [comment]
@Snugug ready for you to review

**Comment by Snugug** [comment]
Look at the rendered versions of the [documentation](https://github.com/ryanbrownhill/design-library/blob/a681f365f82a59d64b1887b2984e4c115636b034/language/ui-patterns/documentation/animation/index.md) and the [guidelines](https://github.com/ryanbrownhill/design-library/blob/a681f365f82a59d64b1887b2984e4c115636b034/language/guidelines/interaction/animation/index.md) and see if what is there makes sense. For instance:

```
**Direction 2**
Both Properties start at the same time then one property ends before the other.
```

Doesn't render on two lines, but one.

**Comment by Snugug** [comment]
* Alt text for images should be in sentence form, so spaces instead of dashed
* Documentation should be human-readable. Many of the sentences read like fragments. Please update.

**Comment by ryanbrownhill** [comment]
@Snugug Travis had an error. It looks like it was an NPM error, how should I go about fixing this?

**Comment by Snugug** [comment]
Hit the refresh button! The circle with an arrow!

**Comment by Snugug** [comment]
@ryanbrownhill A couple of comments left to work on.

**Comment by Snugug** [comment]
A couple of remaining thoughts:

* Instead of listing all of the animatable properties, simply point to that website.
* Provided animations should be in code ticks
* Instead of `Entrances = `, something like `**Entrances** - ` under your Timing Functions

Otherwise. looks good!

**Comment by ryanbrownhill** [comment]
@Snugug do we want to link to http://www.w3schools.com/cssref/css_animatable.asp ? or is there another resources that is perfered?

**Comment by Snugug** [comment]
Absolutely not. W3 schools is crap. The link you currently have is great. Maybe just reword the tag to include seeing a full list of the properties and examples of them animating

**Comment by ryanbrownhill** [comment]
Ohhh ok good to know :ok_hand: no W3 Schools

**Comment by Snugug** [comment]
Okay! This is :+1: from me!
@IBM-Watson/design-acceleration, jump on it!

http://33.media.tumblr.com/9a4c7b8406df7fab1117863cbff2759e/tumblr_mf6ua24pRf1r1mtsdo4_r1_250.gif

**Comment by britanyponvelle** [comment]
:+1:

**Comment by Snugug** [comment]
Resolves #186

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by Snugug** [comment]
That's 3 :+1: 
It's going in!

**Pull request merged**
