### PR TITLE
Add numeric prefixes to folders

### LINKED ISSUE #233: Correctly ordered folders
Add appropriate prefixes to folders so that they display in the correct order (per the [information architecture](https://github.com/IBM-Watson/design-library/wiki/Information-Architecture-for-the-final-site) spelled out in the wiki)

### PR DESCRIPTION
**Pull request by bobbinrobyn**
Resolves #233

### CODE REVIEW

**Comment by bobbinrobyn** [comment]
Weird, why is it grabbing the commits I made to a different branch?

**Comment by Snugug** [comment]
Did you check out your Develop branch, pull from `upstream-develop`, create a new branch, push the new branch, then start working? Or did you create your new branch from one you were already on?

**Comment by bobbinrobyn** [comment]
I'm thinking the answer to that is no. But I closed my terminal somewhere in there, so I can't be sure. I'm really sorry that my interactions with the terminal and GitHub are such a struggle.

**Comment by bobbinrobyn** [comment]
@Snugug I will really do my best to follow every single step next time I make a new branch :flushed: But for now, is this okay or should I make a new branch and then commit these changes again?

**Comment by ryanbrownhill** [comment]
:+1: if @bobbinrobyn  doesn't have to make a new branch to redo the PR.

**Comment by Snugug** [comment]
Please roll a new PR

**Comment by bobbinrobyn** [comment]
Okay, I'll hold off on redoing this until after some of the other PRs get merged in.

**Comment by Snugug** [comment]
I'm going to close this so we can get the other PRs in, then you can make a new PR to get everything in

**Pull request closed without merging**
