### PR TITLE
Sass Cleanup

### LINKED ISSUE #201: Clean Sass usage
How our patterns get used in the library site and how they're defined needs to be cleaned up to support Eyeglass and Import Once.

- [x] Update to use the `index` patter for `base`, `components`, and `layouts`
- [x] Rename `crick` to `_watson-patterns`
- [x] Add Sass file to `library` and import main WDG file
- [x] Update **runner** to compile from `library`
- [x] Update **runner* to compile compressed CSS

### PR DESCRIPTION
**Pull request by Snugug**
Resolves #201

### CODE REVIEW

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by britanyponvelle** [comment]
:+1:

**Comment by britanyponvelle** [comment]
:heart:

**Comment by poofichu** [comment]
:dancer:

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
Resolves #201

**Pull request merged**
