### PR TITLE
Cleanup Style > Typography

### LINKED ISSUE #298: Cleanup Style > Typography
Proofread and fix typos

### PR DESCRIPTION
**Pull request by bobbinrobyn**
Resolves #298 

CHANGELOG
:bug: Fix typos
:bug: Switch back to single quotes
:bug: Switch everything to single quotes

### CODE REVIEW

**Comment by ryanbrownhill** [comment]
:boy: says :green_heart: so this is ready for :+1: !

**Comment by bobbinrobyn** [comment]
@Snugug: I don't think it's a capital L! But maybe you're seeing something I'm not?

But I did go ahead and rework that paragraph to help it make more sense.

**Comment by Snugug** [comment]
Oh wow, you're right. It's just a really weird typeface they're using for the diff.

:+1:

**Comment by ryanbrownhill** [comment]
:+1: looks good to me

**Comment by bobbinrobyn** [comment]
@poofichu: You can :+1: and merge!

**Pull request merged**
