### PR TITLE
Add homepage html

### PR DESCRIPTION
**Pull request by poofichu**
References #121 

CHANGELOG:
:memo: Add html to index.html
Create folder language/images/homepage
Add teal Watson logo homepage asset to language/images/homepage/
:art: Optimize svg file
:memo: Give main full page layout capability
:memo: Add styling for banner
:memo: Add styling for home
:memo: Add styling for what is Watson
:memo: Modify _library--container to work with full width page
:memo: Change base text color from black to gray 90
:memo: Allow containers to work with rhythm
:memo: Position banner image
:memo: Center footer text for small screens

### CODE REVIEW

**Comment by Snugug** [comment]
Please update `library/templates/_layout.html` with the following line:

`<main {% if not layout.index %}library-class="_library--container"{% else %}library-class="_library--stretch-container"{% endif %}>`

**Comment by Snugug** [comment]
Just those two updates and you're :+1:

**Comment by Snugug** [comment]
Why was `logo-watson-t.svg` removed?

**Comment by poofichu** [comment]
Wasn't removed, just optimized.  All code is down to one line.

**Comment by Snugug** [comment]
Truth!

**Comment by poofichu** [comment]
List of things to discuss with @Snugug:

[ ] Largest type setting for small screens
[ ] Top and bottom margin on home section
[ ] Width/margin/padding of child divs on home section
[ ] Default text shadow and background-image on "buttons"
[ ] Footer needs text-align: center for small screens
[ ] Back to top?  What to do with it on the homepage :-/

**Pull request merged**
