### PR TITLE
Pattern/loading indicator

### PR DESCRIPTION
**Pull request by ryanbrownhill**
Minimized SVG Loading Indicator without Clipping Path

### CODE REVIEW

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by Snugug** [comment]
FYI, this branch is on this repo, not on your fork.

**Comment by Snugug** [comment]
:+1:

**Comment by Snugug** [comment]
Related to #322

Resolves #333

**Comment by ryanbrownhill** [comment]
@Snugug whoops :flushed: I cloned this repo and didn't make a fork.....

**Comment by Snugug** [comment]
No worries, BUT NEXT TIME!

**Pull request merged**
