### PR TITLE
Update Color and Accessibility text. 

### PR DESCRIPTION
**Pull request by joshkimmell**
Resolves https://github.com/IBM-Watson/design-library/issues/278.

### CODE REVIEW

**Comment by bobbinrobyn** [comment]
Wooo, your first PR!

**Comment by bobbinrobyn** [comment]
These are all the comments about changes Kathryn wanted to make to these pages: 

Guidelines>Style>Accessibility
Animation
Second sentence: "Do not include anything that flashes, or can be considered a flash, more than twice per second; it can negatively affect those prone to seizures. (2.3a)” change the last part to “it can potentially cause seizures."

Guidelines>Style>Color
Intro Paragraph
delete “our” in front of visual vernacular
Colors for Watson
do we need to include in this paragraph that this is for product design? It states “across all user experiences” but a marketing person might not understand that this term means/includes “product design”.
maybe refer to the internal color workshop blog post for additional information on why the colors were chosen?
Choosing a Color Palette
In title: make the “a” lowercase
“Use the IBM Design Language for a wider variety…” to “Refer to the IBM Design Language for a wider variety…"
"as some users are sensitive to brightness and high contrast colors” change to: “as it softens the ___ for users who are sensitive to brightness and high contrast colors.
Add a period after “Choose a primary and secondary color” and “Choose supporting grays and neutrals"
Make “gray” lower case in “Choose supporting grays and neutrals"
Applying a Color Palette
In title: make the “a” lowercase
First sentence: "Color is a powerful communication tool that helps determine hierarchy on a page."

**Comment by bobbinrobyn** [comment]
And this is the line that @britanyponvelle and I wanted to include about the accessibility of our neutrals:

Colors at a 50 value or lower are *not* accessible on neutral backgrounds, unless they’re displayed at 18 pt or larger. There are no formal color contrast requirements for icons or glyphs that are paired with supporting text. If an icon is used separately from supporting text on a neutral background, use a color value of 50 or higher.

**Comment by joshkimmell** [comment]
Okay... I'll add these changes to the pull request.

**Comment by joshkimmell** [comment]
@bobbinrobyn: should I put that paragraph on the color page or the accessibility page?

**Comment by bobbinrobyn** [comment]
We think it should go on the Accessibility page, between the first example and the "Animation" header.

We also think it would benefit from a visual example so that that text doesn't get lost. I can work on that before the end of the day today, if you want! What do you think?

**Comment by joshkimmell** [comment]
great!

**Comment by bobbinrobyn** [comment]
Once Travis passes, this has my :+1: 

And once this is merged in, I can add the visual examples to the Accessibility page

**Comment by Snugug** [comment]
:+1: 

Once this is merged, we're gonna need to [update our grayscale in code](https://github.com/IBM-Watson/design-library/blob/develop/patterns/core/sass/settings/_colors.scss)

**Pull request merged**
