### PR TITLE
Update color values

### LINKED ISSUE #389: Change the numerical values of the neutrals
We need to change the values of the neutrals to 1, 2, and 4, as opposed to using 10, 20, and 40, for two reasons:

1. IBM Design uses 1, 2, and 4.
2. If we use 10, 20, and 40, it makes it look like the neutrals were designed to fit in the 10-grade accessibility system. They weren't. If they work within it, it's a total accident. So we don't want anyone subtracting Blue 60 from Neutral 10 and just assuming that it's accessible.

image

### PR DESCRIPTION
**Pull request by bobbinrobyn**
Resolves #389

CHANGELOG
:bug: Update neutral color names
:bug: Update neutral color values on Accessibility page

### CODE REVIEW

**Comment by Snugug** [comment]
:no_entry_sign: The IBM Design colors do not define a color palette "Neutral", they define "Neutral-White", "Warm-White", and "Cool-White". (https://github.com/IBM-Design/colors/blob/master/_ibm-colors.scss)

**Comment by bobbinrobyn** [comment]
@Snugug Fair enough. I was looking at the .ase palette from IBM Design, which labels them as "Neutral," "Warm," and "Cool."

**Comment by Snugug** [comment]
Should we close this then?

**Comment by bobbinrobyn** [comment]
@snugug I would say not yet, because it should still say Neutral-White 1, Neutral-White 2, etc.

**Comment by bobbinrobyn** [comment]
When I get a chance to work on that, I'll update this PR

**Pull request closed without merging**
