### PR TITLE
Library/footer

### PR DESCRIPTION
**Pull request by Snugug**
Relates to #224

### CODE REVIEW

**Comment by poofichu** [comment]
:+1: :smile_cat:

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by britanyponvelle** [comment]
:+1:

**Comment by joshkimmell** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
:+1: Should I merge this?

**Comment by Snugug** [comment]
If it looks good to everyone, do it!

**Comment by Lhuihui** [comment]
:+1:

**Pull request merged**
