### PR TITLE
Add Approved Licenses

### LINKED ISSUE #222: Update licenses to approved licenses
We need to update our licensing to the newly approved licenses:

CC-BY 4.0 for Documentation/Assets

Apache 2.0 for source code

### PR DESCRIPTION
**Pull request by Snugug**
Resolves #222

### CODE REVIEW

**Comment by ryanbrownhill** [comment]
New Licenses :+1:  YAYY :tada:

**Comment by Snugug** [comment]
That took me way too many commits to get right.

**Comment by ryanbrownhill** [comment]
Just a couple :stuck_out_tongue_winking_eye: 
I love `Now that it's a markdown file, it works!`

**Comment by ryanbrownhill** [comment]
Resolves #222

**Comment by Snugug** [comment]
…well, it does. :P

**Pull request merged**
