### PR TITLE
Cleanup patterns

### LINKED ISSUE #267: Update Patterns to Align With Guidelines
There are a few things we do throughout our patterns that no longer align to our guidelines. Specifically, I'm seeing colors being used (especially in greyscale) that aren't part of our greyscale, use of alpha transparency, and mixing with black/white for tint/shade instead of using `color-tint` and `color-shade` functions from [IBM Design Colors](https://github.com/IBM-Design/colors#color-tint) to actually move up and down the color tints and shades.

We need to go through all of our patterns and ensure they're conforming to our guidelines as we've set them out.

### PR DESCRIPTION
**Pull request by bobbinrobyn**
Resolves #267, #294, and #335 

CHANGELOG
:bug: Remove Input-Image until a later release
:memo: Change blockquote quote and add citation
:bug: Change italicized citations to font-style: initial
:bug: Change background color of the entire website from pure white to Neutral 20
:bug: Update button styling and add hover states
:art: Update check box styling
:art: Update radio button styling
:bug: Change background color of entire website back to pure white so that orange 50 text is accessible
:bug: Delete extra css & map files, update input styling
:bug: Delete datetime pattern and update spacing of code blocks
:art: Add background to disabled input field
:bug: Update range styling
:bug: Update paragraph styling
:bug: Update styling for patterns

### CODE REVIEW

**Comment by bobbinrobyn** [comment]
Don't :+1: this just yet. @poofichu and I are still working on the patterns and we'll finish it up tomorrow!

**Comment by Snugug** [comment]
Relates to #338

**Comment by Snugug** [comment]
Resolves #294
Resolves #267

**Comment by bobbinrobyn** [comment]
Okay, this is ready for :+1: once Travis passes!

**Comment by bobbinrobyn** [comment]
For changing *55 files* and only having one mistake... I'm feeling pretty good ;)

**Comment by Snugug** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by kathrynmcelroy** [comment]
:+1:

**Pull request merged**
