### PR TITLE
Update to inputs

### LINKED ISSUE #294: Correctly rendered patterns
Some of these patterns are rendering weird...

- [x] [Buttons](http://watsondesign.guide/ui-patterns/patterns/base/button/) - these are tiny, and they don't really look like our buttons
- [x] [Input-Color](http://watsondesign.guide/ui-patterns/patterns/base/input--color/) - there should probably be some kind of indication that clicking will bring up the color picker
- [x] [Input-Image](http://watsondesign.guide/ui-patterns/patterns/base/input--image/) - why is there a button that says submit? This isn't at all what I would expect for an image input.
- [x] [Input-Month](http://watsondesign.guide/ui-patterns/patterns/base/input--month/) - I expected this to be a dropdown with a list of months, as opposed to a calendar. Anybody else?
- [ ] [Input-Range](http://watsondesign.guide/ui-patterns/patterns/base/input--range/) - really just the disabled state. It's still clickable?
- [x] [Input-Week](http://watsondesign.guide/ui-patterns/patterns/base/input--week/) - those controls are tiny! And weirdly arranged...
- [x] [Loading Indicator](http://watsondesign.guide/ui-patterns/patterns/components/loading-indicator/) - rendered pattern doesn't show up (#331)
- [x] border around inputs should get thicker on focus
- [ ] border around search input gets TOO thick on focus

### PR DESCRIPTION
**Pull request by bobbinrobyn**
Partially resolves #294 

CHANGELOG
:bug: Change thickness of border on focus

### CODE REVIEW

**Comment by bobbinrobyn** [comment]
This is ready for :+1:

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by kathrynmcelroy** [comment]
:+1:

**Comment by Snugug** [comment]
Two questions:

1. Is that `1px` extra significant enough that we really need to make a distinction?
2. Do we want this to be the focus style for everything? If so, we should consider moving outline/focus rom inputs to the `body` pattern

**Comment by poofichu** [comment]
@Snugug 1 - I'm okay with it just being the one pixel.  If we absolutely have to put it up to 2px, we can but it's already screaming at me.

2 - Yes por favor!!

**Comment by Snugug** [comment]
I'm going to merge this, then we can have a separate PR to do the full `:focus` stuff

**Pull request merged**
