### PR TITLE
JS Config and Render

### LINKED ISSUE #210: Add JavaScript Configuration and Rendering
Configuration and rendering for our JavaScript

- [x] Add `js.yaml` file to `library/config` configured for the JavaScript 
- [x] Add [PrismJS](http://prismjs.com/) dependency
- [x] Update Library template to point to generated files
- [x] Updated `runner` to compile JS files from config

### PR DESCRIPTION
**Pull request by Snugug**
Resolves #210

### CODE REVIEW

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by Snugug** [comment]
Did you even look at it @ryanbrownhill? :P

**Comment by ryanbrownhill** [comment]
@Snugug  - Yeah I looked a while ago, before travis tested. :smile:

**Comment by Snugug** [comment]
did you?
DID YOU?!

**Comment by britanyponvelle** [comment]
:+1:

**Comment by poofichu** [comment]
:tada: :+1: :dancer: :dango:

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
Resolves #210

**Pull request merged**
