### PR TITLE
Add Exit Animation to SVG Animation & Minified Version

### PR DESCRIPTION
**Pull request by ryanbrownhill**
Add Exit Animation
Add Minified Version of SVG

Relates to #333 & #207

### CODE REVIEW

**Comment by Snugug** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by Snugug** [comment]
You can't :+1: your own thing Ryan!

**Comment by ryanbrownhill** [comment]
:disappointed:

**Comment by Snugug** [comment]
Don't be sad! Be happy! This is GTG
happy elephant

**Comment by bobbinrobyn** [comment]
:+1:

**Pull request merged**
