### PR TITLE
Update Accessibility examples

### LINKED ISSUE #374: Outline text on accessibility SVGs
The text isn't outlined, so it's rendering weird in Firefox.

### PR DESCRIPTION
**Pull request by bobbinrobyn**
(I know this won't get merged in today. It's no big deal.)

Resolves #374 

CHANGELOG
:bug: Outline text on SVGs

### CODE REVIEW

**Comment by bobbinrobyn** [comment]
Ready for :+1:!

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by kathrynmcelroy** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
Again we need to minimize this svg... :/

**Pull request merged**
