### PR TITLE
Intros for patterns sections

### LINKED ISSUE #270: Intro for Patterns Sections
Each pattern section (base/components, maybe layouts) need an intro paragraph and related Language markdown file. Guideline content type. If we don't want to include one for Layouts quite yet because we don't have any, that's cool, let's not include it,

- [x] `ui-patterns/patterns/base` - Base Elements
- [x] `ui-patterns/patterns/components` - Components
- [x] `ui-patterns/patterns/layouts` - Layouts

### PR DESCRIPTION
**Pull request by bobbinrobyn**
Resolves #270 

CHANGELOG
:art: Add type to front matter
:art: Change name of sub-folder to Base
:memo: Create intro page for Components
:memo: Create intro page for Layouts
:fire: Delete Layouts folder until we have layouts to display

### CODE REVIEW

**Comment by bobbinrobyn** [comment]
This is ready for review and :+1:!

**Comment by Snugug** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
I went ahead and did the Layouts page because we already have the content written. Will there be a way to choose to not display it? Or should I just not include it?

**Comment by Snugug** [comment]
Only way to not display it is to not include it

**Comment by bobbinrobyn** [comment]
Noted. I'll delete it.

**Comment by Snugug** [comment]
:+1:

**Comment by Snugug** [comment]
Travis, I'm bored waiting for you.

**Pull request merged**
