### PR TITLE
Update sub-content templates for Color

### LINKED ISSUE #250: Update sub-content templates for Color
Exchange the placeholders for the real deal, according to the templates in the [Content Models](https://github.com/IBM-Watson/design-library/wiki/Content-Models)

### PR DESCRIPTION
**Pull request by bobbinrobyn**
Resolves #250

### CODE REVIEW

**Comment by ryanbrownhill** [comment]
:+1: Looks good to me

**Comment by bobbinrobyn** [comment]
Okay, let's make sure I'm doing this right. If these are the variables:

```
variables:
  example:
    paletteApplication:
      light:
        title: "Example: Light Palette"
        visualDisplay: /images/color/light-palette.svg
        description: "Primary: Blue 60, Secondary: Orange 50, Accent: Teal 40"
        caption: "Consider users who are sensitive to brightness and high contrast colors by using a neutral value as a background color instead of pure white."
      dark:
      title: "Example: Dark Palette"
      visualDisplay: /images/color/dark-palette.svg
      description: "Primary: Blue 30, Secondary: Orange 30, Accent: Teal 30"
      caption: "Consider users who are sensitive to brightness and high contrast colors by using a Gray value as a background color instead of pure black."
```

Then this is how I should write the example templates?
`{{ _example.large(example.paletteApplication.light) }}`
`{{ _example.large(example.paletteApplication.dark) }}`

**Comment by bobbinrobyn** [comment]
@Snugug here's my hundredth question for the day... ^^^

**Comment by Snugug** [comment]
Your items in `dark` need to be indented, but otherwise yup!

**Comment by bobbinrobyn** [comment]
Awesome, thank you!

**Comment by bobbinrobyn** [comment]
Okay, templates are rendering! Woooo! (But no visuals are displaying yet. Assuming that will get fixed when @Snugug's hotfix gets merged?)

**Comment by bobbinrobyn** [comment]
@IBM-Watson/design-acceleration: This is ready for :+1:!

**Comment by britanyponvelle** [comment]
:+1:

**Comment by Snugug** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
Will merge this when it lets me.

**Pull request merged**
