### PR TITLE
Added Motion Guidelines and Images folder

### PR DESCRIPTION
**Pull request by ryanbrownhill**
Resolving issue #114

### CODE REVIEW

**Comment by Snugug** [comment]
Couple of thoughts:

* Please rename the markdown file `motion-guidelines.md`. The `feature/motion-guidelines` is for the branch name.
* Blocks of code should [be fenced](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks). Here, specifically, you should use `scss`
* The `animatable-properties.png` image should be an actual list, not an image
* I'd put the images inside of a `motion` folder arranged just how you do now, but change `example-animations` to just `examples`.
* Is there a reason our easing examples aren't in CSS?
* Please make sure you have [Editorconfig](http://editorconfig.org/) installed and running in your browser of choice, and re-save your Markdown file (or re-save it in an editor that supports it). Some things (like your tabs) aren't quite right with our configuration.
* Some of the copy is incorrect when it comes to the code (specifically how we've implemented animation stuff). You can either [look how](https://github.com/IBM-Watson/design-library/blob/develop/patterns/core/sass/variables/_animations.scss) we have [implemented it](https://github.com/IBM-Watson/design-library/blob/develop/patterns/core/sass/mixins/_animations.scss) and update it yourself, or let me do it after it's merged in
* I recommend you include [frontmatter](http://jekyllrb.com/docs/frontmatter/) in the head of this document in order to allow us to capture meta-data about it. Specifically, I'd include its title, like the following:

```
---
title: Motion Guidelines
---
```

**Comment by Snugug** [comment]
A couple of other technical writing things:

* Avoid the use of first and second person pronouns (I, me, you, et…). Instead try not to write as if you are talking directly to an individual but addressing a large crowd. Either do not address the group you're talking to directly (preferred) or if you must address them directly, do so with `one` or a similar pronoun.
* Lists with only one item should not be a list, but should be a sentence/paragraph/etc… Same goes with headings.
* Headings should be reserved for stand-alone concepts that can work as navigation on the page. Having multiple "Easing Curves" sections may be better suited for simply strong text and explanation underneath
* We may want a bit of pre-amble in each main section (second level header) to describe what the reader will learn in this section and why it's important. Generally speaking, each header should have some long-form text associated with it that makes it unique
* You can link to headers by including a hashed version of their name. For instance, you can link to `Single Property Animations` using `[single property animations](#single-property-animations)`
* Avoid `:` in headers
* "Thought Leader"-esque documentation (for lack of a better term) like we have here should tell a cohesive story that can either be read top to bottom as one long-form narrative. We should work on making these guidelines do so.

**Comment by ryanbrownhill** [comment]
Ok I will update accordingly. I will let you know there are any road bumps
along the way. Thanks for laying it out for me.


On Saturday, March 21, 2015, Sam Richard <notifications@github.com> wrote:

> Couple of thoughts:
>
>    - Please rename the markdown file motion-guidelines.md. The
>    feature/motion-guidelines is for the branch name.
>    - Blocks of code should be fenced
>    <https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks>.
>    Here, specifically, you should use scss
>    - The animatable-properties.png image should be an actual list, not an
>    image
>    - I'd put the images inside of a motion folder arranged just how you
>    do now, but change example-animations to just examples.
>    - Is there a reason our easing examples aren't in CSS?
>    - Please make sure you have Editorconfig <http://editorconfig.org/>
>    installed and running in your browser of choice, and re-save your Markdown
>    file (or re-save it in an editor that supports it). Some things (like your
>    tabs) aren't quite right with our configuration.
>    - Some of the copy is incorrect when it comes to the code
>    (specifically how we've implemented animation stuff). You can either look
>    how
>    <https://github.com/IBM-Watson/design-library/blob/develop/patterns/core/sass/variables/_animations.scss>
>    we have implemented it
>    <https://github.com/IBM-Watson/design-library/blob/develop/patterns/core/sass/mixins/_animations.scss>
>    and update it yourself, or let me do it after it's merged in
>    - I recommend you include frontmatter
>    <http://jekyllrb.com/docs/frontmatter/> in the head of this document
>    in order to allow us to capture meta-data about it. Specifically, I'd
>    include its title, like the following:
>
> ---
> title: Motion Guidelines
> ---
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IBM-Watson/design-library/pull/128#issuecomment-84458912>
> .
>


-- 
-Ryan G. Brownhill
ryanbrownhill.com
ryanbrownhill@gmail.com

**Comment by Snugug** [comment]
No worries, thanks. Let me know how I can help if you need any.

**Comment by ryanbrownhill** [comment]
@Snugug I am moving this to the Wiki until we have the content ironed out. This is also where the Visual Guidelines live right now - so it made the most since. After my discussion with @kathrynmcelroy what I have written seems more like documentation vs. guidelines. We need to have a discussion about the difference Guidelines vs. Documentation and where they will live. etc.

**Pull request closed without merging**
