### PR TITLE
Update sub-content templates for Principles > Inform Interactions

### LINKED ISSUE #246: Update sub-content template for Principles > Inform Interactions
Exchange the placeholder for the real deal, according to the templates in the [Content Models](https://github.com/IBM-Watson/design-library/wiki/Content-Models)

### PR DESCRIPTION
**Pull request by bobbinrobyn**
Resolves #246

### CODE REVIEW

**Comment by bobbinrobyn** [comment]
As far as I can tell, this is ready for :+1:!

**Comment by britanyponvelle** [comment]
:+1:

**Comment by Snugug** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
:+1:

**Pull request merged**
