### PR TITLE
Add visual example files to Performance

### PR DESCRIPTION
**Pull request by poofichu**
Reference #263 

CHANGELOG:
Create folder language/performance/images
Add performance1.svg to language/performance/images
:memo: Add path to image on markdown file
Create folder language/performance/videos
Add performance2.webm video
:memo: Add path to video on markdown file

### CODE REVIEW

**Comment by Snugug** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
:+1:  once travis is happy

**Comment by ryanbrownhill** [comment]
TRAVIS IS HAPPY!! :+1: :tada:

**Comment by bobbinrobyn** [comment]
:+1:

**Pull request merged**
