### PR TITLE
Add Visual Asset to Performance Page

### LINKED ISSUE #263: Create Visual Examples for Performance Guidelines
Reference #215 
and http://una.im/slides-nom-nom-perf/img/Jakob-Nielsen-response-time-infographic.jpg

### PR DESCRIPTION
**Pull request by poofichu**
Resolves #263 

CHANGELOG
:art: Create folder language/performance/images
:art: Add performance1.svg to language/performance/images
:memo: Add path to image on markdown file
:art: Create folder language/performance/videos
:art: Add performance2.webm video
:memo: Add path to video on markdown file

### CODE REVIEW

**Comment by Snugug** [comment]
But… it wasn't added to the page…

**Comment by poofichu** [comment]
Yeah, oops #multitasking
On it.

**Comment by ryanbrownhill** [comment]
@poofichu I can give you a .webm version of the FPS/Hertz video to include in this PR or I can just wait til this get merged and add the video myself. Whichever you prefer, just let me know.

**Comment by poofichu** [comment]
@ryanbrownhill Since I need to redo the markdown file anyways, let's just add it in tomorrow :)

**Comment by ryanbrownhill** [comment]
:ok_hand:

**Comment by Snugug** [comment]
:cry: this can't be merged. Can you re-roll now that everything's merged in?

**Pull request closed without merging**
