### PR TITLE
Update ALL the rhythm

### LINKED ISSUE #330: Set the Rhythm
Play with the rhythm setting to get the right spacing flow throughout the site.

### PR DESCRIPTION
**Pull request by Snugug**
Resolves #330

### CODE REVIEW

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by kathrynmcelroy** [comment]
:+1:

**Comment by poofichu** [comment]
:+1: YEAH GIRL

**Pull request merged**
