### PR TITLE
Feature/color update

### PR DESCRIPTION
**Pull request by Snugug**
Followup to https://github.com/IBM-Watson/design-library/pull/308#issuecomment-102190664

### CODE REVIEW

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by britanyponvelle** [comment]
Looks like you cleaner up the grays primarily?

**Comment by Snugug** [comment]
Added Grey 30 and updated the numbers for all the grays accordingly

**Comment by Snugug** [comment]
Didn't update anything to use Gray 30 (that'll be part of overall styling cleanup)

**Comment by britanyponvelle** [comment]
Cool!! :+1:

**Pull request merged**
