### PR TITLE
Link to Performance page from Typography page

### LINKED ISSUE #400: Link to Performance page from Typography
Thanks for pointing this out, @kathrynmcelroy. http://watsondesign.guide/guidelines/style/typography/

image

### PR DESCRIPTION
**Pull request by bobbinrobyn**
Resolves #400 

CHANGELOG
:art: Add link to Performance page

### CODE REVIEW

**Comment by bobbinrobyn** [comment]
This can use :+1:!

**Comment by kathrynmcelroy** [comment]
We're trying to minimize the use of "we" in the copy, so I would prefer "IBM Watson" or "Watson designers use". Let's discuss this tomorrow.

**Comment by Snugug** [comment]
The Major Third type scale section should be titled something like responsive typography and should talk about our changing modular scale. Don't know if that's out of scope for this pr

**Comment by bobbinrobyn** [comment]
@kathrynmcelroy I was just trying to kill two birds with one stone, but yeah, I don't love the use of "we" but we also need to remove redundant uses of "IBM Watson." When you reword these sentences to just say "Watson," they don't make sense.

Regardless, I'll revert those changes and we can address this in the actual issue (#402).

And for @Snugug, I agree about changing that title & copy, but yes, I think that's out of scope. I'll make a new issue.

**Comment by Snugug** [comment]
:+1:

**Pull request merged**
