### PR TITLE
Add bottom padding to back to top link on homepage

### LINKED ISSUE #370: Back to Top on Homepage
Fix me!

Needs some padding/margin/rhythm love around it.

image

### PR DESCRIPTION
**Pull request by poofichu**
Resolves #370 

`DCO 1.1 Signed-off-by: Jessica Tremblay <tremblay@us.ibm.com>`

### CODE REVIEW

**Comment by poofichu** [comment]
@Snugug noted.

But putting it directly in the _home.scss file targets that element only for the homepage, correct?

**Comment by Snugug** [comment]
Nope

It's just a file naming convention to help us keep track of what stuff we're putting in there. It doesn't scope it.

**Comment by Snugug** [comment]
Please sign off on the [Developer Certificate of Origin](https://github.com/IBM-Watson/design-library/blob/develop/CONTRIBUTING.md#developer-certificate-of-origin) before this can be merged

**Comment by poofichu** [comment]
@Snugug DCO added at the top comment

**Comment by bobbinrobyn** [comment]
:+1:

**Pull request merged**
