### PR TITLE
Add Developing for the Watson Design Library link to Contributing guidelines

### LINKED ISSUE #232: Reference Developing for Design Library from Contributing
We should reference the [Developing for the Design Library](https://github.com/IBM-Watson/design-library/wiki/Developing-for-the-Design-Library) page from the Contributing guidelines.

### PR DESCRIPTION
**Pull request by Snugug**
Resolves #232

### CODE REVIEW

**Comment by bobbinrobyn** [comment]
Looks good to me! :+1:

**Comment by ryanbrownhill** [comment]
:+1: YAyy links!

**Comment by Snugug** [comment]
One more and we can merge this in

**Comment by kathrynmcelroy** [comment]
:+1:

**Comment by Snugug** [comment]
Someone merge this baby in!

**Pull request merged**
