### PR TITLE
Update pattern template

### LINKED ISSUE #191: Update patterns template
Once we have the content and design finished for #188 Elements, #189 Components, and #190 Layouts, we should update the template to make sure it's displaying all of the correct information for each pattern, in the right order.

https://github.com/IBM-Watson/design-library/blob/develop/library/templates/_pattern.html

### PR DESCRIPTION
**Pull request by bobbinrobyn**
Resolves #191 

CHANGELOG
:fire: Remove Rendered Pattern and Pattern Code headings from pattern template
:art: Add function to display Application Methods in the pattern template
:memo: Revise pattern template for Application Methods and include Settings
:art: Update pattern template with revised classes and descriptions

### CODE REVIEW

**Comment by bobbinrobyn** [comment]
Okay, I updated Application Methods according to @Snugug's comment, included the same type of thing for Settings, and added headers for both of them. This is ready for review (and hopefully :+1:)!

**Comment by bobbinrobyn** [comment]
@Snugug: Does every `code` tag need this styling? `code class="language-html base--code"`

**Comment by Snugug** [comment]
@bobbinrobyn no. One the ones wrapped in `pre` tags do

**Comment by bobbinrobyn** [comment]
@Snugug: When you get a chance, check this out and see how it looks!

**Comment by Snugug** [comment]
@bobbinrobyn One small typo, once fixed, :+1:

**Comment by bobbinrobyn** [comment]
You got it @Snugug! Thanks for catching that. @poofichu and @ryanbrownhill, can I get :+1: from y'all?

**Comment by poofichu** [comment]
:+1: :cake:

**Comment by Snugug** [comment]
You too Travis. How boring are you today.

**Pull request merged**
