### PR TITLE
Pattern Syntax Highlighting

### LINKED ISSUE #189: Content & Design for Components page
This page lives here: /UIpatterns/patterns/components

- [x] Write intro paragraph
- [x] Design page
- [ ] Format for production

### PR DESCRIPTION
**Pull request by britanyponvelle**
Resolves #189 and  #137

**CHANGELOG**
- :memo: Add Readme.md for the usage of pattern
- :fire: remove extends
- Add HTML for code block preview
- Add Sass for syntax highlighting using Prism

### CODE REVIEW

**Comment by Snugug** [comment]
* `syntax-highlighting.html` should be an HTML code example, not CSS.
* I see lots of color variables in [your Sass file](https://github.com/britanyponvelle/design-library/blob/43b7b5cd0a81d52c845a8b9d519975c6b5f31581/patterns/components/syntax-highlighting/sass/_syntax-highlighting.scss) We don't have any color variables. Please look at the [IBM Color module](https://github.com/IBM-Design/colors) to see how to use colors. Also, no hex colors
* We already have a bunch of styling in [pre](https://github.com/IBM-Watson/design-library/tree/develop/patterns/base/pre) and [code](https://github.com/IBM-Watson/design-library/tree/develop/patterns/base/code). If styling is generally for all `pre` and `code` tags, should be in there
* Our tab size should be 2
* Why are we constraining the height of our code block? Scrolling code vertically isn't happy. Especially if you have to scroll horizontally as well
* Your `pattern.yaml` file is missing [Application Methods](https://github.com/IBM-Watson/design-library/wiki/Content-Models#pattern)
* Your README needs to be fleshed out to provide more information as to what this does, why you'd use it, etc…
* You accidentally committed `npm-debug.log` into the project. Please remove it (at the root of the project)

**Comment by britanyponvelle** [comment]
@Snugug would the Sass colors look like this?

`.token.punctuation {
  color: 'blue', 80;
}`

**Comment by ryanbrownhill** [comment]
@britanyponvelle like this `$color--secondary: color('green', 40);`

**Comment by ryanbrownhill** [comment]
@britanyponvelle https://github.com/IBM-Design/colors

**Comment by ryanbrownhill** [comment]
I believe it is something like this:

```.token.punctuation { 
color: color('blue', 80);
}``

**Comment by britanyponvelle** [comment]
For the yml file, I copied the format of pattern.yml in the radiogroup component, but I don't seem "application methods" there. Can you show an example?

screen shot 2015-04-30 at 4 37 47 pm

**Comment by britanyponvelle** [comment]
Still need to update:

- Application Methods
- fleshed out ReadMe

**Comment by britanyponvelle** [comment]
@Snugug does "application methods" belong in the README file?

**Comment by Snugug** [comment]
For now, yeah, put it in there. There's a large cleanup project we need to do on our patterns that we can move them then

**Comment by britanyponvelle** [comment]
Ok!

**Comment by Snugug** [comment]
Please remove `js/prism.js`. Instead, in the README, make sure you link to the Prism website and tell the user to include it from its Bower folder

**Comment by Snugug** [comment]
It appears as if the dark backgrounds and light text didn't make it in to the styling here. I'd add the following to your Sass:

```scss
pre[class^="language-"],
pre[class*=" language-"] {
  background: color('gray', 80); // or whatever this color should be

 > code[class^="language-"],
 > code[class*=" language-"] {
    color: color('gray', 20); // or whatever this color should be
  }
}
```

What that code will do is say "When we have a `pre` tag that has a class on it in the form of `language-`, make its background dark. When we have that _and_ we have a `code` tag with the same type of class on it, make the `code`'s color light"

**Comment by britanyponvelle** [comment]
@ryanbrownhill that is a good catch. I will add back ticks!

**Comment by ryanbrownhill** [comment]
Yayy looks good to me! :+1:

**Comment by ryanbrownhill** [comment]
@IBM-Watson/design-acceleration Can we get :+1: ?

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by britanyponvelle** [comment]
:+1:

**Comment by Snugug** [comment]
:no_entry_sign: Please update [the HTML example](https://github.com/britanyponvelle/design-library/blob/9f086a76266f1c7201f60da117c806a2a8c90abc/patterns/components/syntax-highlighting/syntax-highlighting.html) to include final rendered HTML, not SWIG

**Comment by Snugug** [comment]
Also, the language for that should be `markup` not `html`

**Comment by Snugug** [comment]
Once those updates are made, :+1:

**Comment by britanyponvelle** [comment]
:+1: woo!

**Comment by poofichu** [comment]
:+1:

**Comment by Snugug** [comment]
Can you please update to a full HTML example?

**Comment by Snugug** [comment]
Not just remove the Swig curly braces

**Comment by britanyponvelle** [comment]
For the full html example, would this work?

``` html
<pre><code class="language-markup">
<form>
<input type="radio" name="sex" value="male" checked>Male
<br>
<input type="radio" name="sex" value="female">Female
</form>
</code></pre>

**Comment by Snugug** [comment]
Let's use:

```html
<pre><code class="language-markup">
  <form>
    <ul role="radiogroup" class="base--radiogroup">
      <li class="radiogroup--item">
          <input role="radio" class="base--radio" type="radio" id="fruit-options--apple" name="fruit" value="apple">
          <label class="base--inline-label" for="fruit-options--apple">Apple</label>
      </li>
      <li class="radiogroup--item">
          <input role="radio" class="base--radio" type="radio" id="fruit-options--banana" name="fruit" value="apple">
          <label class="base--inline-label" for="fruit-options--banana">Banana</label>
      </li>
      <li class="radiogroup--item">
          <input role="radio" class="base--radio" type="radio" id="fruit-options--orange" name="fruit" value="apple">
          <label class="base--inline-label" for="fruit-options--orange">Orange</label>
      </li>
    </ul>
  </form>
</code></pre>
```

**Comment by britanyponvelle** [comment]
Okay, thank you!!

**Comment by Snugug** [comment]
:+1: Let's merge this sucker

**Comment by ryanbrownhill** [comment]
:+1:  YAY!

**Comment by ryanbrownhill** [comment]
@IBM-Watson/design-acceleration :+1: ?

**Comment by britanyponvelle** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
:+1:

**Pull request merged**
