### PR TITLE
Update Pattern/base style

### PR DESCRIPTION
**Pull request by Lhuihui**
CHANGELOG:

- :fire: delete light font weight in _typography.scss
- Update a: color, text-decoration, font-weight
- Update blockquote: border color, text color, padding
- Update h1: font weight
- Update h3: font weight, color
- Update h4: font style, font weight, color
- Update h5: font weight, color
- Update h6: font style, font weight, color
- Update strong: font weight

### CODE REVIEW

**Comment by Snugug** [comment]
The comments above apply to all patterns.

Additionally, there are a few places where a color is called directly; instead of calling it directly, please make a setting for it so it can be user configurable. Dark grey text won't work on dark backgrounds, so allowing users to change it is preferred.

**Comment by Lhuihui** [comment]
@Snugug Not sure how to do it, can you give me an example? - "instead of calling it directly, please make a setting for it so it can be user configurable"

**Comment by Lhuihui** [comment]
Removing underline looks like a little bit unexpected, but not sure whether there was any accessibility attention behind it. Instead of greying them out, maybe we can make the teal darker? Again, not sure about accessibility

**Comment by Snugug** [comment]
@Lhuihui It actually goes against accessibility requirements to remove the underline on hover/focus. My recommendation is to add an outline on focus.

**Comment by poofichu** [comment]
I want @britanyponvelle to take a look at this one when she can.

I would say maybe turn darkest grey on hover.  No preference on outline for focus.  Seems like a good idea!

**Comment by Lhuihui** [comment]
CHANGELOG:

Update color call in checkbox, input--color, input--range, radio and table


Something need to be done:
1. Britany's final say about a base style
2. Update base style for "code", probably @Snugug can be responsible for that

**Pull request merged**
