### PR TITLE
Hotfix/subcontent templates

### LINKED ISSUE #255: Update Subcontent Templates
There are a handful of bugs in the subcontent templates. They need to be updated.

- [ ] Updated Media handling for all templates that use it (switch ref to `_media`)
- [ ] Update Example sentiment handling to reference actual item

### PR DESCRIPTION
**Pull request by Snugug**
Resolves #255

### CODE REVIEW

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by poofichu** [comment]
:+1: :hamster: :hammer:

**Comment by ryanbrownhill** [comment]
@IBM-Watson/design-acceleration :+1: ?

**Comment by britanyponvelle** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
:+1:

**Pull request merged**
