### PR TITLE
Update 404 Markdown File

### LINKED ISSUE #156: 404 Error page

### PR DESCRIPTION
**Pull request by poofichu**
Resolves #156 and other pull request #213 

CHANGELOG
:art: New url for UI Patterns
:art: Update branch name
:art: Add ligature for icon font
:art: Update paths to URLS
:art: Update "next" to "go"
:art: Update class to library class

### CODE REVIEW

**Comment by Snugug** [comment]
* The URLs need to be absolute urls (`/ui-patterns`, not `ui-patterns`)
* Are we using an icon font or SVG icons? If it's a font, we don't need the `--NEXT`, we can simply have the `icon`. Also, is `(next)` the right word to be using here? We can have the same icon for multiple ligatures, maybe `(go)` makes more sense here?

**Comment by poofichu** [comment]
# will fix the urls
# @bobbinrobyn @kathrynmcelroy ideas on what it should read for a screen reader?

**Comment by poofichu** [comment]
Okay we decided on "go".

**Comment by ryanbrownhill** [comment]
:+1: looks good to me - the changes above have been made.

**Comment by Snugug** [comment]
The Span should be `library-class`, not `class`. Otherwise, :+1:

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
@IBM-Watson/design-acceleration :+1: ?

**Comment by kathrynmcelroy** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by britanyponvelle** [comment]
:+1:

**Pull request merged**
