### PR TITLE
Cleanup Style > Grids

### LINKED ISSUE #305: Cleanup Style > Grids
Proofread for readability & consistent tone

### PR DESCRIPTION
**Pull request by bobbinrobyn**
Resolves #305 

CHANGELOG
:memo: Rework some parts of Grids content to decrease the use of 'we'
:memo: Reword a few more things

### CODE REVIEW

**Comment by bobbinrobyn** [comment]
This is ready for :+1:

**Comment by bobbinrobyn** [comment]
Ugh. False. Travis changed his mind.

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
We're green, we're green! #fullsteamahead

**Pull request merged**
