### PR TITLE
Feature/resource panel

### PR DESCRIPTION
**Pull request by Snugug**
This doesn't resolve any open issue but rather is related to multiple issues dealing with the design of pages

### CODE REVIEW

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by Snugug** [comment]
@IBM-Watson/design-acceleration :+1:s needed!

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
@britanyponvelle If you :+1:, then you can merge it!

**Pull request merged**
