### PR TITLE
feature/syntax

### LINKED ISSUE #137: feature/syntax-highlighting
A component to track our token coloring for [Prism](http://prismjs.com/) for syntax highlighted code blocks.

### PR DESCRIPTION
**Pull request by britanyponvelle**
Added syntax highlight colors from IBM color palette.

Resolves #137

### CODE REVIEW

**Comment by ryanbrownhill** [comment]
:+1: looks good to me

**Comment by britanyponvelle** [comment]
:+1:

**Comment by britanyponvelle** [comment]
@IBM-Watson/design-acceleration can I get a :+1: ?

**Comment by Snugug** [comment]
There are a bunch of updates I'd like to make to this, haven't had time to chat about it. Let's set up some time.

**Comment by Snugug** [comment]
:no_entry_sign: Not ready yet

**Comment by britanyponvelle** [comment]
@Snugug what do you need from me to get this resolved?

**Comment by Snugug** [comment]
Let's set up a meeting today or tomorrow to go over it; there are a bunch of things I'd like to cover with you.

**Comment by britanyponvelle** [comment]
Ok! Your schedule looks packed today and tomorrow, so I picked a random time. Feel free to counter :)

**Comment by Snugug** [comment]
Closing in favor of #208

**Pull request closed without merging**
