### PR TITLE
Library/header

### PR DESCRIPTION
**Pull request by Lhuihui**
CHANGELOG
Add components and global folder in sass folder
Import _heading.scss,  _layout.scss  _variable.scss
Update header section of _layout.html
Change class to library class in sass files

### CODE REVIEW

**Comment by Lhuihui** [comment]
@Snugug The logo is not populating correctly in the header.

**Comment by Snugug** [comment]
* Working on an update to the runner for the logo to populate correctlly
* Please review our [Contributing Guidelines](https://github.com/IBM-Watson/design-library/blob/develop/CONTRIBUTING.md) for commit message style guide
* In the future, please make more than one commit for all files. We want to commit individually, not al at once
* The CHANGELOG wasn't updated, it needs to be updated.
* _All_ classes in `style.scss` need to be attribute selectors for the `library-class` attribute. No regular classes.
* This should only include styling and variables directly related to the header/sidebar/layout. No other variables or styles.

I'm going to do line-by-line comments for the rest.

**Comment by Snugug** [comment]
Once these issues are resolved, I'll start reviewing the content of the styling

**Comment by Snugug** [comment]
The runner has been updated to allow image assets to be copied over from the library folder. Run `vagrant provision` to update your Vagrant box

**Comment by Snugug** [comment]
Closing this based on our conversation yesterday.

**Pull request closed without merging**
