### PR TITLE
Add MP4 files for all videos

### LINKED ISSUE #287: Automatically generate MP4 videos
We have `.webm` videos, but `.mp4` videos should also be available to [cover browsers that don't support `.webm`](http://caniuse.com/#search=webm)

### PR DESCRIPTION
**Pull request by Snugug**
Resolves #287

### CODE REVIEW

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
Videos from the Animation Documentation were not included in this.

**Comment by Snugug** [comment]
They were added after I branched!
Adding them now

**Comment by ryanbrownhill** [comment]
@Snugug have you viewed the .mp4's to check for teal or black lines?

**Comment by Snugug** [comment]
I have not, I will now though

**Comment by Snugug** [comment]
@ryanbrownhill Only the framerate one,  has issues in webm and mp4

**Comment by ryanbrownhill** [comment]
@Snugug ok I updated that one its in #302

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by poofichu** [comment]
:+1: :kissing:

**Pull request merged**
