### PR TITLE
Pattern/Loading Indicator

### LINKED ISSUE #65: Feature/Loading Indicator
Loading indicator component when we don't know percent done (should use #63 when we do)

### PR DESCRIPTION
**Pull request by ryanbrownhill**
Resolves #65 

**CHANGELOG**
- :memo: Add Readme.md for the usage of pattern
- Add IMG files for loader
- Add Modernizr JS with SMIL & SVG detection
- Add HTML with base loading indicator pattern
- Add Sass for styling and fallbacks of loader

### CODE REVIEW

**Comment by ryanbrownhill** [comment]
@Snugug  I don't know what I did but the Animation lIbrary commits came with this branch for some reason... Sorry...

**Comment by Snugug** [comment]
@ryanbrownhill Not a problem. Partner with @britanyponvelle to go over the steps of creating a new branch. I went over them with her the other day.

**Comment by ryanbrownhill** [comment]
It is a new branch that's the weird part. I will do it again with britany
later today.


On Thursday, April 30, 2015, Sam Richard <notifications@github.com> wrote:

> @ryanbrownhill <https://github.com/ryanbrownhill> Not a problem. Partner
> with @britanyponvelle <https://github.com/britanyponvelle> to go over the
> steps of creating a new branch. I went over them with her the other day.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IBM-Watson/design-library/pull/206#issuecomment-97883749>
> .
>


-- 
-Ryan G. Brownhill
ryanbrownhill.com
ryanbrownhill@gmail.com

**Comment by Snugug** [comment]
:\ it looks like we may need to re-roll both of these based on the commits you have in here. We'll see what we need to do.

If you need help, LMK and I can partner with you both to help

**Pull request closed without merging**
