### PR TITLE
Add visual image examples for Typography

### PR DESCRIPTION
**Pull request by poofichu**
References #276 

CHANGELOG
:art: Create image folder
:art: Add svg files to folder images/typography

### CODE REVIEW

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by Snugug** [comment]
Absolute URLs please! `/images/…`

**Comment by Snugug** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
@ryanbrownhill You can :+1: and merge!

**Comment by ryanbrownhill** [comment]
:+1: mergin'

**Pull request merged**
