### PR TITLE
Updated files for Grids Page

### LINKED ISSUE #125: Grid Recommendations
Write recommendations for determining a fluid grid system

### PR DESCRIPTION
**Pull request by poofichu**
...r Grids page

Resolves #125

### CODE REVIEW

**Comment by Snugug** [comment]
Get with @bobbinrobyn and @britanyponvelle to sort out your tab/space issue. You should have `Editorconfig` installed in your editor and tabs should be 2 spaces instead of a full tab. I just talked with @bobbinrobyn about this too.

**Comment by Snugug** [comment]
When you've updated everything, simply commit and push your code back up, no need to create a new PR.

**Comment by Snugug** [comment]
@poofichu This build failed because of your spaces (specifically, dem tabs). Fix that and re-push your changes and we can go from there

**Comment by Snugug** [comment]
@poofichu You didn't fix your YAML! This error is all you, simply fix all of the tabs in your YAML to 2 spaces.

**Comment by kathrynmcelroy** [comment]
Checked the copy - :+1:

**Comment by Snugug** [comment]
As per #152, can you please move the markdown files to the following locations?

`grid-guidelines.md` -> `guidelines/style/grids/index.md`

Thank you much!

**Comment by Snugug** [comment]
Also, please move your grid examples from `*/visual` to `*/grids`. I'd like to keep the various assets as orderly as possible.

**Comment by Snugug** [comment]
Please remove https://github.com/IBM-Watson/design-library/wiki/Grids once merged

**Comment by ryanbrownhill** [comment]
@poofichu once assets are moved around :+1: for me

**Comment by britanyponvelle** [comment]
Content looks good to me :+1:

**Comment by Snugug** [comment]
Can you update the title and CHANGELOG to follow out [contributing guidelines](https://github.com/IBM-Watson/design-library/blob/develop/CONTRIBUTING.md#pull-requests) to make this easier to scan? Thanks!

**Comment by poofichu** [comment]
Will do!

**Comment by Snugug** [comment]
@poofichu There are still a few comments above that need to be addressed before this can be merged in

**Comment by poofichu** [comment]
Resolves #125 
CHANGELOG
:art: add grids folder
:art: move markdown file to new grids folder

**Comment by Snugug** [comment]
Why did you merge `develop` into your branch?

**Comment by poofichu** [comment]
Crap.  Probably accidentally did that yesterday.  I needed to get the most updated version to see the file structure you guys had.

**Comment by Snugug** [comment]
@poofichu You need to move your assets too please!

**Comment by poofichu** [comment]
Resolves #125 
CHANGELOG
:art: move svgs to images/grids folder
:art: move video to videos/grids folder
:art: update file paths in markdown file

**Comment by Snugug** [comment]
:+1:

**Comment by britanyponvelle** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
:+1:

**Pull request merged**
