### PR TITLE
Add sub-content templates

### LINKED ISSUE #193: Create Sub-Content Templates
The following sub-content types need [macro templates](https://github.com/IBM-Watson/design-library/tree/develop/library/templates/subcontent).

~~-[Value](https://github.com/IBM-Watson/design-library/wiki/Content-Models#value)~~
- [x] [Example](https://github.com/IBM-Watson/design-library/wiki/Content-Models#example) (compare)
- [x] [Example](https://github.com/IBM-Watson/design-library/wiki/Content-Models#example) (stand-alone)
- [x] [Aside](https://github.com/IBM-Watson/design-library/wiki/Content-Models#aside)
- [x] [Block Quote](https://github.com/IBM-Watson/design-library/wiki/Content-Models#block-quote)
- [x] [Color Swatches](https://github.com/IBM-Watson/design-library/wiki/Content-Models#color-swatch)
- [x] [Detail](https://github.com/IBM-Watson/design-library/wiki/Content-Models#detail)

### PR DESCRIPTION
**Pull request by Snugug**
Resolves #193 

CHANGELOG committed.

### CODE REVIEW

**Comment by britanyponvelle** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by Snugug** [comment]
One more :+1: and this can get merged

**Comment by ryanbrownhill** [comment]
:+1: Resolves #193

**Pull request merged**
