### PR TITLE
Fix broken links

### LINKED ISSUE #391: Fix broken links
- [x] three primary colors
- [x] Linda van Deursen
- [x] Sass and CSS Development Guidelines
- [x] JavaScript Development Guidelines
- [x] typographic scale

http://watsondesign.guide/guidelines/branding/wordmark/
image

http://watsondesign.guide/guidelines/style/grids/
image

http://watsondesign.guide/ui-patterns/documentation/getting-started/
image
image

http://watsondesign.guide/guidelines/style/grids/
image

### PR DESCRIPTION
**Pull request by bobbinrobyn**
Resolves #391 

CHANGELOG
:bug: Fix broken link on Wordmark page
:bug: Fix broken link on Grids page

### CODE REVIEW

**Comment by bobbinrobyn** [comment]
This isn't done yet, but I didn't want to forget the commits I already did. So let's hold off on :+1: until I get more advice about the blockers on #391.

**Comment by Snugug** [comment]
@bobbinrobyn Updates on this?

**Comment by bobbinrobyn** [comment]
Working on it now!

**Comment by Snugug** [comment]
Please sign off on the [Developer Certificate of Origin](https://github.com/IBM-Watson/design-library/blob/develop/CONTRIBUTING.md#developer-certificate-of-origin) before this can be merged

**Comment by bobbinrobyn** [comment]
I redid this and submitted a new PR. So now I'm going to close this!

**Pull request closed without merging**
