### PR TITLE
Change Details to Animation Examples

### LINKED ISSUE #148: Design for Animation Page
Visual design for Guidelines> Animation page.

### PR DESCRIPTION
**Pull request by bobbinrobyn**
Resolves #148 

**CHANGELOG**
:memo: change details to examples
:art: swap placeholder for actual template
:art: change name of the example variable to examples

### CODE REVIEW

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
Gosh, I feel like I've done this multiple times today. But I think this is actually it.

**Comment by bobbinrobyn** [comment]
@IBM-Watson/design-acceleration If I get some :+1: can we merge this?

**Comment by ryanbrownhill** [comment]
:+1: Double checked and still looks good to me :heart_eyes:

**Comment by poofichu** [comment]
:tada: :tangerine: :+1:

**Comment by britanyponvelle** [comment]
:+1:

**Comment by Snugug** [comment]
Before this gets merged, please update the rendering to use the new templates we have! I've described how to use them in the [content models](https://github.com/IBM-Watson/design-library/wiki/Content-Models)

**Comment by bobbinrobyn** [comment]
Updated! Now is this ready to merge?

**Comment by Snugug** [comment]
@bobbinrobyn ping, comment

**Comment by bobbinrobyn** [comment]
@Snugug That was my question about singular or plural. Which needs to change, the variable or the template?

**Comment by Snugug** [comment]
@bobbinrobyn The template doesn't need to change, the thing that's important is that the name of the thing you pass in and the name it's stored as in the YAML file are the same.

When working with functions (this is a function), they look like the following:

```javascript
function myFunction (myArg)
```

The `myArg` is the placeholder for the thing you're passing in to the function, but its name and the name of the thing you're passing in don't need to match. `myArg` will be used by the function so it doesn't need to know the name of the thing you're passing it; think of it as a nickname for the thing you're passing in. As the writer of the function, I don't need to know the person's name as long as they respond to the nickname I give them.

**Comment by bobbinrobyn** [comment]
Bahhh, I forgot the emoji. Sorry.

**Comment by bobbinrobyn** [comment]
Thanks for the explanation @Snugug!

**Comment by Snugug** [comment]
@bobbinrobyn Don't worry about the "we can't automatically merge" message. If this looks good to everyone, I'll do a manual merge and test.

**Comment by Snugug** [comment]
And don't worry about the Emoji!

**Comment by ryanbrownhill** [comment]
This looks good to me :+1:

**Comment by bobbinrobyn** [comment]
Thanks @Snugug!

**Comment by britanyponvelle** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
@Snugug @poofichu :+1: ?

**Comment by poofichu** [comment]
Bueno! :+1:

**Comment by ryanbrownhill** [comment]
@Snugug Looks ready for a black magic time merge.... :octocat:

**Comment by Snugug** [comment]
Hey @bobbinrobyn! This PR is being made into the `language/animation` branch. Can you please close this and re-open it against the `develop` branch? Thank you!

**Pull request closed without merging**
