### PR TITLE
Update layout template to new navigation variables

### LINKED ISSUE #195: Update layout template to new navigation variables
Once ibm-watson/runner#12 gets merged in, there will be a need to update the layout template to the newest variables.

### PR DESCRIPTION
**Pull request by Snugug**
Does not update to final HTML, just SWIG structure for rendering

Resolves #195

### CODE REVIEW

**Comment by britanyponvelle** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by Snugug** [comment]
Resolves #37 as well once everything gets merged in and a release is rolled.

**Comment by Snugug** [comment]
Activates #161

**Pull request merged**
