### PR TITLE
Update sub-content templates for Grids

### LINKED ISSUE #239: Update sub-content template for Grids
Exchange the placeholder for the real deal, according to the templates in the [Content Models](https://github.com/IBM-Watson/design-library/wiki/Content-Models)

### PR DESCRIPTION
**Pull request by bobbinrobyn**
Resolves #239

### CODE REVIEW

**Comment by bobbinrobyn** [comment]
@Snugug: I see the first set of examples, but I don't see the second example (not even the text). Is that a concern?

**Comment by bobbinrobyn** [comment]
Never mind, I got it. Getting better at catching mistakes :wink:

**Comment by bobbinrobyn** [comment]
This is ready for :+1:!

**Comment by britanyponvelle** [comment]
:+1:

**Comment by Snugug** [comment]
:+1:

**Pull request merged**
