### PR TITLE
Update to Animation guidelines and documentation

### LINKED ISSUE #148: Design for Animation Page
Visual design for Guidelines> Animation page.

### PR DESCRIPTION
**Pull request by bobbinrobyn**
Resolves #148 and #226 

CHANGELOG
:memo: change details to examples
:art: swap placeholder for actual template
:art: change name of the example variable to examples
:art: correct typos and wording in animation documentation

### CODE REVIEW

**Comment by ryanbrownhill** [comment]
:+1: updated `example` to `examples`

**Comment by ryanbrownhill** [comment]
@IBM-Watson/design-acceleration  :+1: ?

**Comment by Snugug** [comment]
Needs to be updated before :+1:s

**Comment by bobbinrobyn** [comment]
@Snugug: Hmmm. I was trying to use the right branch naming terminology `language/animation`, but we have two different Animation pages... the one in Guidelines and the one in UI Patterns. So now I made it all confused.

**Comment by Snugug** [comment]
@bobbinrobyn The one in UI Patterns is documentation for the animation bits of the Pattern Library. The one in Guidelines is the guideline

**Comment by bobbinrobyn** [comment]
Yep, and now I've contributed markdown files for both, and they're sitting right here in the same PR. I feel like that's wrong.

**Comment by bobbinrobyn** [comment]
@Snugug: Should I have made a new branch to keep my most recent changes to the Animation documentation separate?

**Comment by Snugug** [comment]
@bobbinrobyn Nope. You should have kept your original branch, and just added a new commit to it.

**Comment by bobbinrobyn** [comment]
@Snugug Oh, excellent. Then I'll just update the PR title!

**Comment by bobbinrobyn** [comment]
Sorry I keep forgetting the emojis...

**Comment by bobbinrobyn** [comment]
@Snugug: What did you mean earlier when you commented that it needed to be updated?

> Needs to be updated before :+1:s

**Comment by Snugug** [comment]
@bobbinrobyn Hmm, I hadn't seen the line that showed it had been updated.

**Comment by bobbinrobyn** [comment]
@Snugug Gotcha. So we're good?

**Comment by Snugug** [comment]
Unfortunately it looks like your latest commit broke our ability to merge this in. Do you think you can re-roll using just the stuff in Guidelines? Sorry and thank you :\

**Comment by bobbinrobyn** [comment]
Sure, but can you help me undo the other change I made? What do I need to do to go back a few steps to before I made this last commit?

**Comment by Snugug** [comment]
I'm going to help you out

**Comment by Snugug** [comment]
The documentation updates didn't get merged in, the other ones did. Please make a new PR for typo fixes for documentation.

**Pull request merged**
