### PR TITLE
Update Accessibility visual example

### LINKED ISSUE #260: Refine Animation visual example
Remove teal from Accessibility image so it doesn't compete with interface colors. 

screen shot 2015-05-07 at 4 01 34 pm
_Teal numbers_

I received feedback from other designers saying that it appeared as though the numbers were apart of the interface, so I am proposing we change it to white.

screen shot 2015-05-07 at 3 57 26 pm
_White numbers_

### PR DESCRIPTION
**Pull request by britanyponvelle**
Resolves #260 

**CHANGELOG**
- Update colors in Accessibility visual example

### CODE REVIEW

**Comment by ryanbrownhill** [comment]
@britanyponvelle :+1: Travis PASSED!

**Comment by Snugug** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
@Snugug: Is 3 :+1: enough? Jessica and Kathryn are busy with interviews today.

**Pull request merged**
