### PR TITLE
Fix wonky italics on UI Patterns > Base

### LINKED ISSUE #360: Update Patterns / Base Copy
http://watsondesign.guide/ui-patterns/patterns/base/

- [ ] un-italicize this section: "(e.g. ::selection, ::root), as well as any custom CSS resetting ("
- [ ]  Check Box
     - [ ]  A form field option where multiple choices may be selected, including, but not requiring this particular element. <- delete this period
- [ ]  Input - Telephone
     - [ ] "Tel input field for a form" - spell out Telephone number input field
- [ ]  Pre
     - [ ]  "Pre-formatted text" - add hyphen
- [ ]  Paragraph
     - [ ] ~~Defines~~ paragraphs of text within a page

### PR DESCRIPTION
**Pull request by bobbinrobyn**
Resolves #360 

CHANGELOG
:bug: Fix wonky italics

### CODE REVIEW

**Comment by kathrynmcelroy** [comment]
:+1:

**Comment by Snugug** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by poofichu** [comment]
:+1: Bueno! :hamburger:

**Pull request merged**
