### PR TITLE
Release v1.0.0-beta-3

### LINKED ISSUE #198: Release v1.0.0-beta-3
Roll a release for v1.0.0-beta-3

### PR DESCRIPTION
**Pull request by Snugug**
:shipit: Release for v1.0.0-beta-3. Resolves #198

### CODE REVIEW

**Comment by britanyponvelle** [comment]
whoa!

**Comment by britanyponvelle** [comment]
:+1:

**Comment by Snugug** [comment]
Because this is being a bit finicky, I'm going to merge this myself, but everyone can comment on it.

**Comment by Snugug** [comment]
OMG IT'S ALL WORKING! NOW JUST NEED TO ENSURE THE URL IS WORKING AS EXPECTED AND WE'RE GOOD TO GO!

**Comment by Snugug** [comment]
Resolves #37

**Comment by Snugug** [comment]
OMG IT IS WORKING! GOING TO MEGE!

**Pull request merged**
