### PR TITLE
Update Wordmark/ Logotype and Accessibility Guidelines

### LINKED ISSUE #142: Design for Wordmark Page
Visual design for Guidelines> Wordmark page.

- [x] Update colors for logo and wordmark

Tied to #141

### PR DESCRIPTION
**Pull request by britanyponvelle**
Resolves #142 and #182 

**CHANGELOG**

* :memo: Update to Accessibility guidelines
* :memo: Update to Wordmark and Logotype guidelines
* :fire: Delete outdated color Wordmark and Logotype SVGs
* :art: Replace updated color Wordmark and Logotype SVGs

### CODE REVIEW

**Comment by britanyponvelle** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
:+1: looks good to me! Love to see :fire: optimizing SVGs!

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
Resolves #142 and #182

**Comment by britanyponvelle** [comment]
@Snugug did I do this right? Just want to make sure

**Comment by Snugug** [comment]
Yes, pretty much! A couple things: :art: should be used for formatting updates, not for images/actual art, Added should be Add, and your 3rd commit message is too long. Instead, consider doing multi-line commits; something like the following:

```
$ git commit -m ":memo: Update Accessibility and Wordmark guidelines" -m ":fire: Delete wordmark and logo SVGs" -m "Add wordmark and logo"
```

Etc… Each `-m` is a new line in the commit. Breaking this commit up in to smaller commits would have also been good.

**Pull request merged**
