### PR TITLE
Order folders correctly

### LINKED ISSUE #233: Correctly ordered folders
Add appropriate prefixes to folders so that they display in the correct order (per the [information architecture](https://github.com/IBM-Watson/design-library/wiki/Information-Architecture-for-the-final-site) spelled out in the wiki)

### PR DESCRIPTION
**Pull request by bobbinrobyn**
Resolves #233

CHANGELOG
:art: Add prefixes to Principles, Guidelines, and UI Patterns
:art: Add prefixes to Principles sub-folders
:art: Add prefixes to Guidelines sub-folders
:art: Add prefixes to UI Patterns sub-folders
:art: Remove prefix from UI Patterns so that it displays properly

### CODE REVIEW

**Comment by Snugug** [comment]
:+1: assuming this goes green

**Comment by bobbinrobyn** [comment]
Okay, hooray! This is ready for :+1:!

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
@poofichu @kathrynmcelroy @britanyponvelle : If one of you wants to :+1:, you can merge it!

**Comment by ryanbrownhill** [comment]
Resolves #233

**Pull request merged**
