### PR TITLE
Fix capitalization on Performance SVG

### LINKED ISSUE #395: Change capitalization on SVG
Switch from title case to sentence case

image

### PR DESCRIPTION
**Pull request by bobbinrobyn**
Resolves #395 

CHANGELOG
:bug: Fix capitalization on SVG

### CODE REVIEW

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by kathrynmcelroy** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
@bobbinrobyn we actually need to minimize this svg.... :/

**Comment by bobbinrobyn** [comment]
@Snugug said he built-in optimization. So no need for us to manually optimize images anymore! But maybe that's different than the minimizing you're talking about?

**Pull request merged**
