### PR TITLE
Change design principles to separate files

### LINKED ISSUE #116: Design principles
- [x] Write design principles
- [x] User test written principles
- [x] Choose headings/titles for principles
- [x] Prototype concepts for visual examples
- [x] User test visual examples
- [x] Synthesize research & iterate
- [x] Write short description for principles
- [x] Write intro paragraph for principles
- [x] Create final visual assets
- [x] Format text & media for production

### PR DESCRIPTION
**Pull request by bobbinrobyn**
This closes #116 

**CHANGELOG**
:memo: :art: Move design principles to individual markdown files

### CODE REVIEW

**Comment by bobbinrobyn** [comment]
Sorryyyy @Snugug. I'm really trying to follow all the rules.

**Comment by Snugug** [comment]
It's ok, no worries! The `:memo: :art:` thing is weird because emoji don't work in titles. It wasn't in the guideliens, just added it because of that. I've made that mistake too (today, actually)

**Comment by Snugug** [comment]
Can you update the title to follow out [contributing guidelines](https://github.com/IBM-Watson/design-library/blob/develop/CONTRIBUTING.md#pull-requests) to make this easier to scan?

**Comment by Snugug** [comment]
Instead of putting each individual file into the `design-principles` folder, can you please make separate sub-folders inside of `language/principles` for each and move each into their respective sub-folders, renaming them `index.md` like all of the other long-form text? Please ensure the sub-folder names are dashed instead of camelCase.

In YAML, the keys should be camelCase, but file and folder names should be dash separated.

Thank you!

**Comment by bobbinrobyn** [comment]
**CHANGELOG**
:art: Add `introduce-cognitive` sub-folder
:art: Add `inform-interactions` sub-folder
:art: Add `offer-control` sub-folder
:art: Move files from `design-principles` respective sub-folders in `language/principles`
:fire: Delete `design-principles` folder
:art: Rename introduce-cognitive.md to index.md
:art: Rename inform-interactions.md to index.md
:art: Rename offer-control.md to index.md

**Comment by Snugug** [comment]
For all of these:

* Don't include the title (H1) in the Markdown file; that's going to get rendered.
* Same conversation from earlier; the tagline can't be a header, it needs to be something like strong paragraph text.

**Comment by bobbinrobyn** [comment]
**CHANGELOG**
:art: Remove H1s
:art: Change H2s to strong paragraph text

**Comment by Snugug** [comment]
:+1: lgtm

**Pull request merged**
