### PR TITLE
Fix Teal Line in Performance Video

### PR DESCRIPTION
**Pull request by ryanbrownhill**
Above ^
Relates to [this comment](https://github.com/IBM-Watson/design-library/issues/263#issuecomment-102003297)

### CODE REVIEW

**Comment by ryanbrownhill** [comment]
:boy: says :green_heart: so its ready for :+1:

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
@Snugug :+1: ?

**Comment by poofichu** [comment]
:+1: :zap:

**Pull request merged**
