### PR TITLE
Bottom Nav Template

### PR DESCRIPTION
**Pull request by Snugug**
Adds HTML scaffolding for bottom nav. Does not resolve the issue.

Relates to #176

### CODE REVIEW

**Comment by ryanbrownhill** [comment]
Looks good to me :+1:

**Comment by poofichu** [comment]
Bueno! :hatched_chick: :+1:

**Comment by Lhuihui** [comment]
Great! We have the "back to top" button as well just above the page nav. Not sure whether it's better in one template or separate templates.

**Comment by Snugug** [comment]
That belongs in this template. I'll update this template to include that

**Comment by Lhuihui** [comment]
We don't have the icon in icon moon file yet. But you can include it now and we update them once we have that icon

**Comment by Snugug** [comment]
Okay team, updated with back to top link. One last review before we merge in

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
:+1: looks good to me :smile:

**Comment by Snugug** [comment]
One more :+1: and this is going on.

**Comment by britanyponvelle** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
Sam :+1: and Travis said :green_heart: so its going in. Also Relates to #176

**Pull request merged**
