### PR TITLE
Update animation documentation

### LINKED ISSUE #226: Revised animation docs
Correct some typos & reword a few sections on the UI Patterns > Documentation > Animation page.

### PR DESCRIPTION
**Pull request by bobbinrobyn**
Resolves #226 

CHANGELOG
:art: correct typos and wording in animation documentation
:art: second attempt to correct typos and wording in animation documentation

### CODE REVIEW

**Comment by bobbinrobyn** [comment]
This is ready for :+1:!

Unfortunately GitHub isn't showing all the changes I made, but @kathrynmcelroy and I worked on this together yesterday to clean up spelling, grammar, and wording stuff.

**Comment by Snugug** [comment]
@bobbinrobyn If it's not showing the changes, that means the changes weren't captured. For instance, I know in your previous changed file that `Using bounces eases to add the snap in` was changed to `Use bounce eases to add the snap-in` or something to that extent. Please double check that your changes are actually present and if not, commit them in

**Comment by bobbinrobyn** [comment]
Okay, we should be good now! My changes are actually committed.

**Comment by Snugug** [comment]
@bobbinrobyn Looks good assuming you get greens!

For your next set of commits, please double-check the [Git Commit Message Style Guide](https://github.com/IBM-Watson/design-library/blob/develop/CONTRIBUTING.md#git-commit-messages) and make sure your commit messages follow it. Don't need to change anything for this, just for next time.

Also, now that you've got the CHANGELOG in your repo, please update the CHANGELOG itself instead of putting your changes into the pull request. Thank you!

**Comment by ryanbrownhill** [comment]
:+1: look good to me and travis

**Comment by bobbinrobyn** [comment]
This is ready for :+1:

**Comment by kathrynmcelroy** [comment]
:+1:

**Pull request merged**
