### PR TITLE
Update color page to reflect new research

### PR DESCRIPTION
**Pull request by poofichu**
We've updated the Color page to reflect the research and concerns from the other visual designers.

Things changed:
- Orange 60 removed from primary
- Secondary colors included all tints and shades of the Watson Color Palette
- Include section about choosing supporting grays and neutrals
- Include section about choosing colors outside Watson Color Palette
- Include 2 examples, a dark and a light
- All tints and shades of the recommended Watson Palette are shown as swatches

`DCO 1.1 Signed-off-by: Jessica Tremblay <tremblay@us.ibm.com>`

### CODE REVIEW

**Comment by poofichu** [comment]
Resolves #417 #429

**Comment by bobbinrobyn** [comment]
Wooo, so much love went into this page! Hopefully Circle gets her act together and passes really soon ;)

**Comment by bobbinrobyn** [comment]
This also resolves #378

**Comment by bobbinrobyn** [comment]
:+1:

**Pull request merged**
