### PR TITLE
Feature/motion guidelines

### LINKED ISSUE #114: Add Motion Guidelines to Library Folder in Repo
- [x] Add Images to img folder
- [x] Add Markdown File.

### PR DESCRIPTION
**Pull request by ryanbrownhill**
Resolves #114 
This markdown is the documentation section for the motion guidelines

Here is the information architecture for the current guidelines based off @kathrynmcelroy 's structure: 

IA Template
---
* General Title
	* Description
		* Section Title
			* Short description
			* introduction description
			* Supporting Principle box
			* Sub Section Title
				* Intro paragraph about section
				* Images supporting paragraph
				* Rendered view of section part
				* Code snippet of section part
				* Supporting Principle box (if needed)

Motion Guidelines IA
--- 

* **Motion Guidelines**
	* Motion is a vehicle ______
	* Value Prop. - Motion is important because
        - **Principles**
            - Short Description
            - Introduction Description
            - **Efficient**
                - Moves with maximum Precision and Productivity
                    - It moves to the point and quick.
                    - Technical: Properties and Time
            - **Graceful**
                - Moves with elegant rhyme and rhythm
                    - Delays are constant across similar content.
                    - Technical: Easing & Delays
            - **Delightful (??)**
                - Moves with charisma, soil and a bit of magic
                    - Building entrances with fast exits.
        - **Best Practices**
            - Link to Interaction Design Guidelines
        - **Education**
            - How to implement animation in the design process
            - **Designing the in betweens**
                - Design the motion between 2 interaction states
                - The HERO Shot (make sure it helps the user)
            - **Prototype the Motion**
                - Using Sketches
                - Using Keynote
                - Using After Effects
            - **Producing Motion in Code**
                - Link to Current Animation Documentation
        - **Foundations of Motion**
            - Short Description
            - Introduction Description
            - **Speed**
                - Intro Paragraph
                - Animations supporting paragraph
                - Code Snippet of support (link out to documentation)
            - **Easing**
                - Intro Paragraph
                - Animations supporting paragraph
                - Code Snippet of support (link out to documentation)
            - **Hierarchy**
                - Intro Paragraph
                - Animations supporting paragraph
                - Code Snippet of support (link out to documentation)
            - **Building Blocks**
                - **Position**
                    - Tab Bar Example
                - **Slide**
                    - Notification
                - **Bounce**
                    - App Icons Hopping
                - **Scale**
                    - Infographic
                - **Expand & Contract**
                    - Search Dropdown
                - **Z-Depth**
                    - Reorder

### CODE REVIEW

**Comment by ryanbrownhill** [comment]
@Snugug feel free to take a look and let me know what you think.

**Comment by Snugug** [comment]
As per #152, can you please move the markdown files to the following locations?

`motion-guidelines.md` -> `guidelines/interaction/animation/index.md`

Thank you much!

**Comment by Snugug** [comment]
Also, please update to reflect our current [Content Models](https://github.com/IBM-Watson/design-library/wiki/Content-Models)

**Comment by ryanbrownhill** [comment]
@Snugug updated via file structure and content models take a look. 
Also #148 has the link to the current prototype that relates to this PR.

**Comment by Snugug** [comment]
Somethings… wrong. I'm investigating.

**Comment by Snugug** [comment]
Just make sure your tabs are right (should be 2 spaces, not a tab) and this is :+1: from me

**Comment by ryanbrownhill** [comment]
@Snugug the tabs were 2 spaces but I retabbed everything just in case.

**Comment by Snugug** [comment]
Please remove https://github.com/IBM-Watson/design-library/wiki/Animation-Documentation and https://github.com/IBM-Watson/design-library/wiki/Animation-Guidelines once merged

**Comment by ryanbrownhill** [comment]
:ok_hand: Please Travis :pray:  - I am counting on you to build successfully :hammer:

**Comment by Snugug** [comment]
:+1: from me. Everyone else?

**Comment by ryanbrownhill** [comment]
Removed from Wiki :fire:

**Pull request merged**
