### PR TITLE
Update content on Wordmark and Logo page

### LINKED ISSUE #204: Update assets and examples on Logo page
Updates needed:

- [x] Add logo with thought rays
- [x]  Remove logotype without thought rays
- [x] update examples
- [x] adjust guidelines accordingly 
- [x] Update all wordmark assets to include the trademark
- [x] Update markdown file

### PR DESCRIPTION
**Pull request by britanyponvelle**
Resolves #204 

**CHANGELOG**
- :memo: Update content to include Logo guidelines
- Change title to "Wordmark and Logo"
- Remove content about logotype
- Add trademark to wordmark
- Refine spacing considerations
- Add "Powered by Watson" to guidelines
- Add "Powered by Watson" and "Ecosystem" assets to download folder

### CODE REVIEW

**Comment by ryanbrownhill** [comment]
:+1: Looks good to me.

**Comment by Snugug** [comment]
As you're in here, can you update to the [Secondary Content Type templates](https://github.com/IBM-Watson/design-library/wiki/Content-Models#secondary-content-types)

**Comment by britanyponvelle** [comment]
Yes, sir!

**Comment by ryanbrownhill** [comment]
:+1: looks good to me, updated via the comments above.

**Comment by britanyponvelle** [comment]
@Snugug is this following the Secondary Content Type template correctly?

**Comment by Snugug** [comment]
@britanyponvelle I think you forgot to push your work/submit your comment?

**Comment by britanyponvelle** [comment]
@Snugug I added them in https://github.com/britanyponvelle/design-library/commit/5cb807cfae908c4441af6dd81ab76e780b19c09d

**Comment by bobbinrobyn** [comment]
@Snugug: I'm curious about using the "compare" example, as well! If you get a chance to double check Britany's work, that would be awesome. Then I'll just follow her lead.

**Comment by Snugug** [comment]
So the place where we would use `compare` is when we have two or more items to compare. It's basically a simple wrapper to let the `small` items sit well with each other. `small` will be a single, small, floated item

**Comment by bobbinrobyn** [comment]
@Snugug: But what kind of variable is it expecting? Especially in a situation where maybe there are a bunch of example variables, but you only want to compare 2 of them.

This is how @britanyponvelle has it:
`{{ _example.compare(example.exampleOne) }}`
`{{ _example.compare(example.exampleTwo) }}`

But maybe it should be like this?
`{{ _example.compare(example.exampleOne, example.exampleTwo) }}`

Or does it need the compare template *and* the small template?
`{{ _example.compare(examples) }}`
`{{ _example.small(example.exampleOne) }}`
`{{ _example.small(example.exampleTwo) }}`

**Comment by Snugug** [comment]
I'd make separate groupings for the different things you want to compare. So, I'd do:

```yaml
example:
  firstCompare:
    exampleOne: stuff
    exampleTwo: stuff
  secondCompare:
    exampleThree: stuff
    exampleFour: stuff
```

Then, do

```
{{ _example.compare(firstCompare) }}
```

**Comment by britanyponvelle** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by Snugug** [comment]
:no_entry_sign: Sorry, I wrote the above too fast. I should be `{{ _example.compare(example.firstCompare) }}`. Please update.

There also seem to be some missing images that are being referenced. Please ensure all images that are referenced are available.

**Comment by britanyponvelle** [comment]
@Snugug should I remove the resources content from this page, since it lives in the footer now?

```
{{> SomeFunctionHere resources}}
```

**Comment by Snugug** [comment]
Yup!

**Comment by britanyponvelle** [comment]
Should the front matter still be there?

```
resources:
  files:
    name: "Wordmark and Logo SVG"
    source: /images/wordmark/watson_wordmark_logotype.zip

**Comment by Snugug** [comment]
@britanyponvelle 

```
resources:
  files:
    - name: "Wordmark and Logo SVG"
      source: /images/wordmark/watson_wordmark_logotype.zip
```

**Comment by Snugug** [comment]
:+1: This can be merged once others do the same.

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
:+1:

**Pull request merged**
